backend:
    name: github
    repo: Miastodwa/jazdow.pl
    branch: master

media_folder: www/.vuepress/public/images
public_folder: www/.vuepress/dist/

display_url: https://jazdow.pl

collections:
    - 
        label: PL Pages
        name: pages_pl
        folder: www/
        filter: {field: generic, value: true}
        fields:
            - 
                label: Title
                name: title
                widget: string
            - 
                label: TLDR
                name: tldr
                widget: text
            -
                label: Body
                name: body
                widget: markdown
            -
                label: Generic
                name: generic
                widget: hidden
                default: true
    -
        label: PL Custom Pages
        name: customPages_pl
        files:
            -
                label: Strona Główna
                name: home_pl
                file: www/README.md
                fields:
                    - {label: Layout, name: layout, widget: hidden}
                    - {label: Intro, name: intro, widget: text}
                    - {label: Body, name: body, widget: markdown}
                    -
                        label: Parallax images
                        name: images
                        widget: list
                        allow_add: false
                        field: {label: image, widget: image}
                        default: [/images/intro/ambasada1.jpg, /images/intro/ambasada2.jpg]
                    -
                        label: Map Card
                        name: mapCard
                        widget: object
                        fields:
                            - {label: Link, name: link, widget: string}
                            - {label: Title, name: title, widget: string}
                            - {label: Caption, name: caption, widget: string}
                    -
                        label: Events Card
                        name: eventsCard
                        widget: object
                        fields:
                            - {label: Link, name: link, widget: string}
                            - {label: Title, name: title, widget: string}
                            - {label: Caption, name: caption, widget: string}
                            - {label: More, name: more, widget: string}
                            - {label: Empty, name: empty, widget: string}
                    -
                        label: Pages Cards
                        name: cards
                        widget: list
                        fields:
                            - {label: Cover, name: cover, widget: image}
                            - {label: Link, name: link, widget: string}
                            - {label: Title, name: title, widget: string}
                            - {label: Caption, name: caption, widget: string}
                    -
                        label: Video sources
                        name: video
                        widget: hidden
                        fields:
                            - {label: mp4 source, name: mp4, widget: string, default: /videos/video.mp4}
                            - {label: webm source, name: webm, widget: string, default: /videos/video.webm}
                            - {label: poster source, name: poster, widget: string, default: /videos/poster.jpg}
                    -
                        label: Subtitles
                        name: subs
                        widget: list
                        fields:
                            - {label: time (seconds), name: t, widget: number, default: 0, min: 0, valueType: float}
                            - {label: text, name: s, widget: string}
            -
                label: Mapa
                name: map_pl
                file: www/mapa.md
                fields:
                    - {name: permalink, widget: hidden, default: mapa}
                    - {label: Layout, name: layout, widget: hidden, default: Map}
                    - {label: Body, name: body, widget: markdown}
                    -
                        label: Legend
                        name: legend
                        widget: hidden
                    -
                        label: Open Houses
                        name: openHouses
                        widget: list
                        fields:
                            - {label: Name, name: Name, widget: string}
                            - {label: Coords, name: coords, widget: string}
                            - {label: Address, name: address, widget: string}
                            - {label: Link, name: link, widget: string, default: ''}
                    -
                        label: ClosedHouses
                        name: closedHouses
                        widget: list
                        fields:
                            - {label: Coords, name: coords, widget: string}
                            - {label: Address, name: address, widget: string}
