backend:
    name: github
    repo: Miastodwa/jazdow.pl
    branch: master

media_folder: www/.vuepress/public/images
public_folder: www/.vuepress/dist/

display_url: https://jazdow.pl

collections:
    - 
        name: pages
        label: Pages
        folder: www/
        filter: {field: generic, value: true}
        fields:
            - 
                label: Title
                name: title
                widget: string
            - 
                label: TLDR
                name: tldr
                widget: text
            -
                label: Body
                name: body
                widget: markdown
            -
                label: Generic
                name: generic
                widget: hidden
                default: true
    -
        name: customPages
        label: Custom Pages
        files:
            -
                name: home_pl
                label: Strona Główna
                file: www/README.md
                fields:
                    - {label: Layout, name: layout, widget: hidden}
                    - {label: Intro, name: intro, widget: text}
                    - {label: Body, name: body, widget: markdown}
                    -
                        label: Parallax images
                        name: images
                        widget: list
                        allow_add: false
                        field: {label: image, widget: image}
                        default: [/images/intro/ambasada1.jpg, /images/intro/ambasada2.jpg]
                    -
                        label: Map Card
                        name: mapCard
                        widget: object
                        fields:
                            - {label: Link, name: link, widget: string}
                            - {label: Title, name: title, widget: string}
                            - {label: Caption, name: caption, widget: string}
                    -
                        label: Events Card
                        name: eventsCard
                        widget: object
                        fields:
                            - {label: Link, name: link, widget: string}
                            - {label: Title, name: title, widget: string}
                            - {label: Caption, name: caption, widget: string}
                            - {label: More, name: more, widget: string}
                            - {label: Empty, name: empty, widget: string}
                    -
                        label: Pages Cards
                        name: cards
                        widget: list
                        fields:
                            - {label: Cover, name: cover, widget: image}
                            - {label: Link, name: link, widget: string}
                            - {label: Title, name: title, widget: string}
                            - {label: Caption, name: caption, widget: string}
                    -
                        label: Video sources
                        name: video
                        widget: hidden
                        fields:
                            - {label: mp4 source, name: mp4, widget: string}
                            - {label: webm source, name: webm, widget: string}
                            - {label: poster source, name: poster, widget: string}
                    -
                        label: Subtitles
                        name: subs
                        widget: list
                        fields:
                            - {label: time (seconds), name: t, widget: number, default: 0, min: 0, valueType: float}
                            - {label: text, name: s, widget: string}